### ISSUE TITLE
With N=2 or more, the profiler hangs

### ISSUE THREAD

**Issue by cdunn2001** [pb-cdunn/nim-debug#2]

**Comment by bpr** [comment]
This works for me on Ubuntu 14.04 with profiling on, by setting the flags 

NIMFLAGS+=--profiler:on
NIMFLAGS+=--stackTrace:on


recompiling and running with N = 2 and 4. I see the file ./test/profile_results.txt and it looks like 

total executions of each stack trace:
Entry: 1/4 Calls: 3/6 = 50.00% [sum: 3; 3/6 = 50.00%]
  kmer_lookup_c.nim: init_kmer_lookup 3/6 = 50.00%
  kmer_lookup_c.nim: allocate_kmer_lookup 3/6 = 50.00%
  falcon.nim: generate_consensus 3/6 = 50.00%
  main.nim: get_con 4/6 = 66.67%
  main.nim: process_consensus 4/6 = 66.67%

for the run with N = 4. What do you get, on which systems?

**Comment by cdunn2001** [comment]
It hung on Ubuntu, for a release build, but only on the larger examples. Try SIZE=long or SIZE=huge.

**Comment by bpr** [comment]
I ran make fail, where 

fail:
        N=2 SIZE=huge make -C test

and it completed and generated a profile file. This is on Ubuntu 14.04.5 LTS. Are you on the same?

**Comment by bpr** [comment]
Just tried again on the same Ubuntu machine with N=4 and today's Nim

Nim Compiler Version 0.16.1 (2017-04-06) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 0c694d2064cbaa3b2dc6aea4a521304ba36963a4
active boot switches: -d:release

and it works again, no hanging.

**Comment by cdunn2001** [comment]
Ok. I'll try again tomorrow...

**Comment by pb-cdunn** [comment]
This particular problem seems to be fixed.
