### ISSUE TITLE
Huge uses 50TB of virtual memory

### ISSUE THREAD

**Issue by pb-cdunn** [pb-cdunn/nim-debug#3]
There is a strange discontinuity in memory use:
```
cd test/
N=24 SIZE=huge make

main(n_core=24)
len(seqs)=25, seed_id=2
tot=4206592 occ=3895296, free=311296 b4
tot=4206592 occ=1511424, free=2695168 now
len(seqs)=98, seed_id=14
tot=12738560 occ=5505024, free=7233536 b4
tot=12738560 occ=5517312, free=7221248 now
len(seqs)=58, seed_id=15
tot=8810496 occ=8105984, free=704512 b4
tot=8810496 occ=5414912, free=3395584 now
len(seqs)=43, seed_id=22
tot=8810496 occ=6955008, free=1855488 b4
tot=8810496 occ=5242880, free=3567616 now
len(seqs)=55, seed_id=25
tot=8810496 occ=6180864, free=2629632 b4
tot=8810496 occ=6184960, free=2625536 now
len(seqs)=39, seed_id=30
tot=8810496 occ=6385664, free=2424832 b4
tot=8810496 occ=6389760, free=2420736 now
len(seqs)=23, seed_id=31
tot=8810496 occ=7843840, free=966656 b4
tot=8810496 occ=6381568, free=2428928 now
len(seqs)=36, seed_id=39
tot=545730560 occ=7839744, free=537890816 b4
tot=545730560 occ=7847936, free=537882624 now
len(seqs)=27, seed_id=40
tot=1082789888 occ=9961472, free=1072828416 b4
tot=1082789888 occ=7696384, free=1075093504 now
len(seqs)=37, seed_id=42
tot=2157912064 occ=11968512, free=2145943552 b4
tot=2157912064 occ=8302592, free=2149609472 now
...
```
Maybe it's not a discontinuity; maybe it's factors of 2 somewhere. While system RAM is stable at about 4GB, virtual memory rises as high as 48TB, though it sometimes drops briefly to 1TB.

**Comment by pb-cdunn** [comment]
@bpr, Can you verify this behavior on Ubuntu? (I haven't tried on Mac yet...) You can try `N=4`; virtual memory still gets pretty high.

I've tried adding a `GC_fullCollect()` into the iteration on the main thread, which I used for the logging shown above. Freemem reported after GC levels off at 2GB on the main thread; virtual memory rises more slowly, but it still gets huge.

**Comment by bpr** [comment]
EDIT:
Just saw your post in the forum, will try again

**Comment by bpr** [comment]
It looks like RAM doubles sometimes in yours. I ran with N=8 and the largest total I see is 46178304, which is 46M, not even close to the 2.6G you have above, and the progression upwards is reasonable, certainly not doubling at larger sizes.

**Comment by bpr** [comment]
What is the machine/configuration you're running this on? Could that be part of the problem?

**Comment by pb-cdunn** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty
```
I just pushed a small bug-fix. I guess you could try building the exact same code I am using. Very odd though. I will try this on Mac soon...

**Comment by pb-cdunn** [comment]
Nope, no problem on Mac.

Note that to see the problem, you need at least one worker thread:

    cd nim-debug/test
    N=1 SIZE=huge make

**Comment by pb-cdunn** [comment]
> It looks like RAM doubles sometimes in yours.

It's not just the doubling. There are moments when memory jumps incredibly:
```
$ N=2 SIZE=huge make
...
thread slot=1
tot=8994816 occ=5869568, free=3125248 b4
tot=8994816 occ=5468160, free=3526656 now
len(seqs)=61, seed_id=78
len(consensus)=36401 in seed 74
thread slot=0
tot=8994816 occ=8179712, free=815104 b4
tot=8994816 occ=6918144, free=2076672 now
len(seqs)=29, seed_id=79
len(consensus)=25475 in seed 75
thread slot=1
tot=8994816 occ=8175616, free=819200 b4
tot=8994816 occ=5853184, free=3141632 now
len(seqs)=52, seed_id=80
len(consensus)=21191 in seed 79
thread slot=1
tot=8599101440 occ=8278016, free=8590823424 b4
tot=8599101440 occ=7950336, free=8591151104 now
len(seqs)=70, seed_id=85
len(consensus)=32493 in seed 78
```
See? Fairly early, it suddenly went from a reasonable 9MB to an unbelievable 8.6GB. When it does that, virtual memory sky-rockets to hundreds of GB.

I'll try running on some other machines in our corporate network...

**Comment by bpr** [comment]
I see nothing like that on my Ubuntu 14.04 run, the memory growth is very even, growing by about 25% each time it gets bumped.

I'm not seeing the behavior that you are. It's a bit of a mystery as to why not, but multithreaded programming is full of surprises.

**Comment by pb-cdunn** [comment]
Yeah, it works great on Centos7. (Nim does not build on Centos6, and araq has said he is not interested in solving that problem. Search `atom` in Issues.)

Virtual memory is stable at about 2x resident mem. Nim is still a little slower than Python, but I know that's because we are re-creating the `msa_array` workspace structure for each thread.  There are things we can try to improve that.
```
Nim:
tot=72273920 occ=45178880, free=27095040 now
real    0m50.247s
user    20m21.961s
sys     3m18.410s

Python:
real    0m32.908s
user    19m40.301s
sys     3m21.769s
```
I guess on Ubuntu, we can just live with the weird virtual mem problems, and maybe it will go away when they reboot the virtual machine I was using.

**Comment by pb-cdunn** [comment]
I can still repro this reliably on all the Ubuntu14 machines I've tried at PacBio, even our login nodes (which might not be virtual machines). I see virtual memory use sky-rocket to 50TB, though it sometimes drops to *only* a few TB. Very weird.

**Comment by bpr** [comment]
I can't reproduce it on my 14.04 machine. I'll try my 16.04 machine. These are all 'native'; I'm not running a VM, the 16.04 machine is a Dell laptop.

**Comment by bpr** [comment]
16.04 just fine, same as before. I didn't see close to 1G of mem used, it topped at 36M.

**Comment by bpr** [comment]
This is really weird, and I'm running out of ideas to debug. You said it happens early in the run. Let stay with N=2 SIZE=huge. Does it happen in the sample place at every run? Do you have environment variables set which may be affecting this? I ask if you have them because I did nothing special and it runs fine on 14.04, 16.04, and OS X for me.

**Comment by pb-cdunn** [comment]
I found some old extra code for the Ubuntu14 runs, where I was altering how threadpool worked at start-up. With that removed, the virtual memory strangeness is gone, so that part was my own mistake.

But the program is still an order of magnitude slower (multi-threaded) on our Ubuntu14 virtual machines.

**Comment by bpr** [comment]
Slower than what? The Python using the multiprocessing lib, the single threaded runs, the multithreaded runs running directly on 14.04 without the vm, ...?

**Comment by pb-cdunn** [comment]
Slower than both the old Python and than Nim on Centos7/Macosx. Way slower. It's disturbing.

**Comment by bpr** [comment]
But, the issue manifests itself only when running on VM?
